### ISSUE TITLE
Investigate RESTful API config layers for Kamailio & RADIUS

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/FIRE-WS#8]

**Comment by tokland** [comment]
Kamailio:

- The standard tool to control kamailio is the CLI tool`kamctl` (ships with the official package):

https://www.kamailio.org/wiki/tutorials/getting-started/main#kamctl

http://manpages.ubuntu.com/manpages/zesty/man8/kamctl.8.html

- `kamctl` is a bash (a single file), so I guess devs found it hard to extend and work with. So on 2015 the kamailio team started  another tool,`kamcli`: https://github.com/kamailio/kamcli This is recommended tool to use, it supports pretty much all `kamctl` commands and some more. It's a python module, so I've checked the source code to see if it's prepared to be used  as a Python module, but it's not. All commands are structured around the CLI infrastructure with no public exports. So the easier will be to call it as a shell command (if it's finally what we use).

**Comment by tokland** [comment]
Radius:

Radius is an extremely complex package, so with just some hours of exposure I am not sure I am missing something. 

- `radmin` is a CLI tool to control a radius server instance, but not to configure it: http://freeradius.org/radiusd/man/radmin.html
- AFAICS, people tend to custom freeradius by using a mysql backend and then directly connecting to the DB to create/update. An example of this approach can be seen here, it's a good example because it's a pretty simple project: https://github.com/lcapriotti/voucherBox/

More on this:

https://wiki.freeradius.org/guide/SQL-HOWTO-for-freeradius-3.x-on-Debian-Ubuntu

**Comment by ifoche** [comment]
Thanks @tokland. We'll talk a little bit more on this in today's meeting, but looks really good your first approach to the question. I guess no RESTful APIs to mention, right?
